<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8xzGsYR\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8xzGsYR/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container8xzGsYR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container8xzGsYR\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \Container8xzGsYR\srcApp_KernelTestDebugContainer([
    'container.build_hash' => '8xzGsYR',
    'container.build_id' => '22a16613',
    'container.build_time' => 1624001407,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8xzGsYR');
