<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOm9DAFC\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOm9DAFC/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerOm9DAFC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerOm9DAFC\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerOm9DAFC\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'Om9DAFC',
    'container.build_id' => 'ed75106a',
    'container.build_time' => 1623920395,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOm9DAFC');
