<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGm7xLKT\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGm7xLKT/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerGm7xLKT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerGm7xLKT\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerGm7xLKT\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'Gm7xLKT',
    'container.build_id' => '3fadf588',
    'container.build_time' => 1623846688,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGm7xLKT');
