<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGW23O43\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGW23O43/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGW23O43.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGW23O43\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGW23O43\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GW23O43',
    'container.build_id' => '330a8a28',
    'container.build_time' => 1623913343,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGW23O43');
