<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAFqdY6w\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAFqdY6w/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAFqdY6w.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAFqdY6w\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAFqdY6w\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AFqdY6w',
    'container.build_id' => 'c179fa18',
    'container.build_time' => 1623737866,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAFqdY6w');
