<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXgKfY01\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXgKfY01/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXgKfY01.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXgKfY01\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXgKfY01\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XgKfY01',
    'container.build_id' => '6f7898c4',
    'container.build_time' => 1624005150,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXgKfY01');
