<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'app_cabinets_findall' => [[], ['_controller' => 'App\\Controller\\CabinetsController::findAll'], [], [['text', '/cabinets']], [], []],
    'app_cabinets_find' => [['id'], ['_controller' => 'App\\Controller\\CabinetsController::find'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/cabinets']], [], []],
    'app_cabinets_newcabinet' => [[], ['_controller' => 'App\\Controller\\CabinetsController::newcabinet'], [], [['text', '/cabinets']], [], []],
    'app_cabinets_deletecabinet' => [['id'], ['_controller' => 'App\\Controller\\CabinetsController::deletecabinet'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/cabinets']], [], []],
    'app_doctor_index' => [[], ['_controller' => 'App\\Controller\\DoctorController::index'], [], [['text', '/doctors']], [], []],
    'app_patients_findall' => [[], ['_controller' => 'App\\Controller\\PatientsController::findAll'], [], [['text', '/patients']], [], []],
    'app_patients_find' => [['id'], ['_controller' => 'App\\Controller\\PatientsController::find'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/patients']], [], []],
    'app_patients_newpatient' => [[], ['_controller' => 'App\\Controller\\PatientsController::newPatient'], [], [['text', '/patients']], [], []],
    'app_patients_deletepatient' => [['id'], ['_controller' => 'App\\Controller\\PatientsController::deletePatient'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/patients']], [], []],
    'app_rendezvous_findall' => [[], ['_controller' => 'App\\Controller\\RendezVousController::findAll'], [], [['text', '/rendezvous']], [], []],
    'app_rendezvous_find' => [['id'], ['_controller' => 'App\\Controller\\RendezVousController::find'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/rendezvous']], [], []],
    'app_rendezvous_delete' => [['id'], ['_controller' => 'App\\Controller\\RendezVousController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/rendezvous']], [], []],
    'app_rendezvous_newrendezvous' => [[], ['_controller' => 'App\\Controller\\RendezVousController::newRendezVous'], [], [['text', '/rendezvous']], [], []],
    'app_rendezvous_deleterendezvous' => [['id'], ['_controller' => 'App\\Controller\\RendezVousController::deleteRendezVous'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/rendezvous']], [], []],
];
